# Generated by Django 3.2.3 on 2021-06-04 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='gantt_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='proposal',
            name='gantt_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
