# Generated by Django 3.2.3 on 2021-06-04 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone_app', '0002_auto_20210604_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='gantt_date',
            new_name='gantt_date_end',
        ),
        migrations.AddField(
            model_name='proposal',
            name='gantt_date_start',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
