# Generated by Django 3.2.3 on 2021-06-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone_app', '0003_auto_20210604_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskItem', models.TextField()),
            ],
        ),
    ]
