# Generated by Django 3.2.3 on 2021-06-08 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone_app', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Capstone_app.proposal'),
            preserve_default=False,
        ),
    ]
