# Generated by Django 3.2.3 on 2021-06-11 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone_app', '0006_auto_20210610_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='gantt_date_end',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='task',
            name='gantt_date_start',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
