# Generated by Django 3.2.3 on 2021-07-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone_app', '0010_auto_20210612_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL_Shortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=800)),
                ('shortened_url', models.CharField(max_length=800)),
            ],
        ),
    ]
