# Generated by Django 3.2.3 on 2021-07-08 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone_app', '0011_url_shortener'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URL_Shortener',
        ),
    ]
